CREATE TABLE product
(
    -- GENERATED ALWAYS prevents inserting id manually
    -- GENERATED BY DEFAULT allows it
    id        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name      TEXT           NOT NULL,
    price     NUMERIC(10, 2) NOT NULL,
    image_url TEXT           NOT NULL
);

CREATE TABLE fulfilment_date
(
    id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE
);


CREATE TABLE fulfillment_date_product
(
    fulfillment_date_id INTEGER NOT NULL REFERENCES fulfilment_date (id) ON DELETE CASCADE,
    product_id          INTEGER NOT NULL REFERENCES product (id)
);