[application]
name = "digeatery"
asset_dir = "asset" # default "assets"
tailwind_output = "asset/tailwind.css" # default "assets/tailwind.css"

[web.app]

# HTML title tag content
title = "digeatery"

# include `asset` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
